version: "3.2"

services:
  watchtower:
    image: agrea/watchtower
    build: .
    environment:
      PORT: 3000
      DATABASE_URL: postgres://watchtower:watchtower@db:5432/watchtower?sslmode=disable
    volumes:
      - type: volume
        source: .
        target: /go/src/github.com/agrea/watchtower
    depends_on:
      - db

  db:
    image: postgres:9.6.5-alpine
    environment:
      POSTGRES_USER: watchtower
      POSTGRES_PASSWORD: watchtower
    ports:
      - "5432:5432"
