version: "3.2"

services:
  watchtower:
    image: agrea/watchtower
    build: .
    environment:
      PORT: 3001
    volumes:
      - type: volume
        source: .
        target: /go/src/github.com/agrea/watchtower
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: host
    command: gin run main.go
    depends_on:
      - db

  db:
    image: postgres:9.6.5-alpine
